"""Removed amount property from cart model

Revision ID: 066ad49b1ca5
Revises: dd87a3b248cb
Create Date: 2023-03-21 11:35:40.914115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066ad49b1ca5'
down_revision = 'dd87a3b248cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('amount', sa.NUMERIC(precision=9, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
