"""Added order id foreign key and fixed, renamed item id to product id, fixed foreign key of product id.

Revision ID: 26ef4bd761ac
Revises: 3118d424b5d1
Create Date: 2023-02-16 12:23:23.194483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ef4bd761ac'
down_revision = '3118d424b5d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_lines', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('order_lines', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_constraint('order_lines_item_id_fkey', 'order_lines', type_='foreignkey')
    op.create_foreign_key(None, 'order_lines', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'order_lines', 'orders', ['order_id'], ['id'])
    op.drop_column('order_lines', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_lines', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order_lines', type_='foreignkey')
    op.drop_constraint(None, 'order_lines', type_='foreignkey')
    op.create_foreign_key('order_lines_item_id_fkey', 'order_lines', 'orders', ['item_id'], ['id'])
    op.drop_column('order_lines', 'product_id')
    op.drop_column('order_lines', 'order_id')
    # ### end Alembic commands ###
