"""Added user id property to the cart model

Revision ID: f47f37fa6bd6
Revises: 066ad49b1ca5
Create Date: 2023-03-23 16:49:41.900259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47f37fa6bd6'
down_revision = '066ad49b1ca5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_column('carts', 'user_id')
    # ### end Alembic commands ###
